### ISSUE TITLE
Automate app build

### ISSUE THREAD

**Issue by AM-ash-OR-AM-I** [AM-ash-OR-AM-I/user_expenses#2]
Flutter supports [github actions](https://github.com/features/actions) to automate app builds on push, [Flutter Actions](https://github.com/marketplace/actions/flutter-action) allow you to build app on push, thus negating the need to build app locally this speeds up development process significantly!

**Comment by amartyaroy** [comment]
Hi @AM-ash-OR-AM-I 
Can you please elaborate what kind of build pipeline you want to create so that I can work in this issue if possible

**Comment by AshuK8s** [comment]
> Hi @AM-ash-OR-AM-I 
> Can you please elaborate what kind of build pipeline you want to create so that I can work in this issue if possible

Hi @amartyaroy! I was referring to building apk on push using GitHub actions workflows (I've referenced a link to it in the above issue). 

What it should do:
- build apk by using workflows whenever code is pushed and then you can download apk from the actions tab instead of having to build it locally every time. Using `.yml` file
- [optional] I'm not sure how to do this but if possible publish the apk release section, basically automating the entire process of app build.
- [optional] Again I've to research this, if it's possible to do the same workflows for other platforms such as Linux or windows (less likely)

**Comment by AshuK8s** [comment]
https://github.com/AM-ash-OR-AM-I/user_expenses/commit/a53f9eeaa55c389bca5356f43d3a1e60a0ef288b Automated build process.
